services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /data/db
  app:
    build:
      context: .
      dockerfile: DockerfileApp
    ports:
      - 8080:8080
    depends_on:
      - mongodb
  jacoco-report:
    build:
      context: .
      dockerfile: DockerfileJacocoReport
    ports:
      - 8081:80