server:
  port: 8080
  error:
    include-message: always

spring:
  data:
    mongodb:
      database: luizalabswishlist
      authentication-database: luizalabswishlist
      repositories: null
      enabled: true
      uri: mongodb://mongodb:27017